// <auto-generated />
using System;
using EnglishCenter.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishCenter.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EnglishCenterDbContext))]
    [Migration("20260926060458_AddNotificationProcessingRecords")]
    partial class AddNotificationProcessingRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.AppUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId")
                        .HasName("PK_AppUsers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_AppUsers_Email");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasDatabaseName("UQ_AppUsers_StudentId")
                        .HasFilter("[student_id] IS NOT NULL");

                    b.HasIndex("TeacherId")
                        .IsUnique()
                        .HasDatabaseName("UQ_AppUsers_TeacherId")
                        .HasFilter("[teacher_id] IS NOT NULL");

                    b.ToTable("AppUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AppUsers_Role", "[role] IN ('ADMIN', 'STAFF', 'TEACHER', 'STUDENT')");
                        });
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<long>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("attendance_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttendanceId"));

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<DateTime?>("CheckInAt")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("check_in_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("EnrollmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("recorded_by");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("AttendanceId")
                        .HasName("PK_AttendanceRecords");

                    b.HasIndex("AttendanceDate", "EnrollmentId")
                        .HasDatabaseName("IX_AttendanceRecords_AttendanceDate");

                    b.HasIndex("EnrollmentId", "AttendanceDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_AttendanceRecords_EnrollmentDate");

                    b.HasIndex("UpdatedAtUtc", "AttendanceId")
                        .HasDatabaseName("IX_AttendanceRecords_UpdatedAtUtc");

                    b.ToTable("AttendanceRecords", null, t =>
                        {
                            t.HasTrigger("TR_AttendanceRecords_SetUpdatedAtUtc");

                            t.HasCheckConstraint("CK_AttendanceRecords_Status", "[status] IN ('PRESENT', 'ABSENT', 'LATE', 'EXCUSED')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            AttendanceId = 1001L,
                            AttendanceDate = new DateOnly(2026, 10, 1),
                            CheckInAt = new DateTime(2026, 10, 1, 18, 25, 0, 0, DateTimeKind.Utc),
                            CreatedAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1001L,
                            IsDeleted = false,
                            RecordedBy = "seed",
                            Status = "PRESENT",
                            UpdatedAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.Class", b =>
                {
                    b.Property<long>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClassId"));

                    b.Property<short>("Capacity")
                        .HasColumnType("smallint")
                        .HasColumnName("capacity");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("class_code");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("class_name");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("RoomName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("room_name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("ScheduleNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("schedule_note");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PLANNED'");

                    b.Property<long?>("TeacherId")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("ClassId")
                        .HasName("PK_Classes");

                    b.HasIndex("ClassCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Classes_ClassCode");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("IX_Classes_CourseId");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("IX_Classes_TeacherId");

                    b.HasIndex("UpdatedAtUtc", "ClassId")
                        .HasDatabaseName("IX_Classes_UpdatedAtUtc");

                    b.ToTable("Classes", null, t =>
                        {
                            t.HasTrigger("TR_Classes_SetUpdatedAtUtc");

                            t.HasCheckConstraint("CK_Classes_Capacity", "[capacity] > 0");

                            t.HasCheckConstraint("CK_Classes_DateRange", "[end_date] >= [start_date]");

                            t.HasCheckConstraint("CK_Classes_Status", "[status] IN ('PLANNED', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            ClassId = 1001L,
                            Capacity = (short)20,
                            ClassCode = "CLS-A1-DEMO-001",
                            ClassName = "A1 Demo Evening Class",
                            CourseId = 1001L,
                            CreatedAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2026, 12, 31),
                            IsDeleted = false,
                            RoomName = "Room A1",
                            ScheduleNote = "Tuesday and Thursday, 18:30-20:00",
                            StartDate = new DateOnly(2026, 10, 1),
                            Status = "OPEN",
                            TeacherId = 1001L,
                            UpdatedAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.Course", b =>
                {
                    b.Property<long>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CourseId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("course_code");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("course_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LevelCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("level_code");

                    b.Property<short>("PlannedHours")
                        .HasColumnType("smallint")
                        .HasColumnName("planned_hours");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<decimal>("StandardTuition")
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("standard_tuition");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'DRAFT'");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("CourseId")
                        .HasName("PK_Courses");

                    b.HasIndex("CourseCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Courses_CourseCode");

                    b.HasIndex("UpdatedAtUtc", "CourseId")
                        .HasDatabaseName("IX_Courses_UpdatedAtUtc");

                    b.ToTable("Courses", null, t =>
                        {
                            t.HasTrigger("TR_Courses_SetUpdatedAtUtc");

                            t.HasCheckConstraint("CK_Courses_PlannedHours", "[planned_hours] > 0");

                            t.HasCheckConstraint("CK_Courses_StandardTuition", "[standard_tuition] >= 0");

                            t.HasCheckConstraint("CK_Courses_Status", "[status] IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            CourseId = 1001L,
                            CourseCode = "ENG-A1-DEMO",
                            CourseName = "English A1 Foundation",
                            CreatedAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deterministic local development seed course.",
                            IsDeleted = false,
                            LevelCode = "A1",
                            PlannedHours = (short)40,
                            StandardTuition = 3000000m,
                            Status = "ACTIVE",
                            UpdatedAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.Enrollment", b =>
                {
                    b.Property<long>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EnrollmentId"));

                    b.Property<decimal>("AgreedTuition")
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("agreed_tuition");

                    b.Property<long>("ClassId")
                        .HasColumnType("bigint")
                        .HasColumnName("class_id");

                    b.Property<string>("CompletionNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("completion_note");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("EnrolledAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("enrolled_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("EnrollmentId")
                        .HasName("PK_Enrollments");

                    b.HasIndex("ClassId", "Status")
                        .HasDatabaseName("IX_Enrollments_ClassIdStatus");

                    b.HasIndex("StudentId", "ClassId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Enrollments_StudentClass");

                    b.HasIndex("UpdatedAtUtc", "EnrollmentId")
                        .HasDatabaseName("IX_Enrollments_UpdatedAtUtc");

                    b.ToTable("Enrollments", null, t =>
                        {
                            t.HasTrigger("TR_Enrollments_SetUpdatedAtUtc");

                            t.HasCheckConstraint("CK_Enrollments_AgreedTuition", "[agreed_tuition] >= 0");

                            t.HasCheckConstraint("CK_Enrollments_Status", "[status] IN ('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'WITHDRAWN')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1001L,
                            AgreedTuition = 2900000m,
                            ClassId = 1001L,
                            CreatedAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrolledAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Status = "ACTIVE",
                            StudentId = 1001L,
                            UpdatedAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.NotificationProcessingRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("event_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("channel");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset(3)")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parameters_json");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("processed_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("RecipientUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("template_key");

                    b.HasKey("EventId")
                        .HasName("PK_NotificationProcessingRecords");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("IX_NotificationProcessingRecords_ProcessedAtUtc");

                    b.ToTable("NotificationProcessingRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_NotificationProcessingRecords_Channel", "[channel] IN ('EMAIL', 'IN_APP')");
                        });
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("EnrollmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payment_reference");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("PaymentId")
                        .HasName("PK_Payments");

                    b.HasIndex("EnrollmentId", "PaymentDate")
                        .HasDatabaseName("IX_Payments_EnrollmentIdPaymentDate");

                    b.HasIndex("UpdatedAtUtc", "PaymentId")
                        .HasDatabaseName("IX_Payments_UpdatedAtUtc");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasTrigger("TR_Payments_SetUpdatedAtUtc");

                            t.HasCheckConstraint("CK_Payments_Amount", "[amount] > 0");

                            t.HasCheckConstraint("CK_Payments_Method", "[payment_method] IN ('CASH', 'BANK_TRANSFER', 'CARD', 'E_WALLET', 'OTHER')");

                            t.HasCheckConstraint("CK_Payments_Status", "[status] IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            PaymentId = 1001L,
                            Amount = 1450000m,
                            CreatedAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            EnrollmentId = 1001L,
                            IsDeleted = false,
                            Note = "Deterministic development seed payment.",
                            PaymentDate = new DateOnly(2026, 9, 25),
                            PaymentMethod = "BANK_TRANSFER",
                            PaymentReference = "DEMO-PAYMENT-001",
                            Status = "COMPLETED",
                            UpdatedAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("refresh_token_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("RefreshTokenId")
                        .HasName("PK_RefreshTokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_RefreshTokens_TokenHash");

                    b.HasIndex("UserId", "ExpiresAtUtc")
                        .HasDatabaseName("IX_RefreshTokens_UserExpiry");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.Student", b =>
                {
                    b.Property<long>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("GuardianName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("guardian_name");

                    b.Property<string>("GuardianPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("guardian_phone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'ACTIVE'");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("student_code");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("StudentId")
                        .HasName("PK_Students");

                    b.HasIndex("StudentCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Students_StudentCode");

                    b.HasIndex("UpdatedAtUtc", "StudentId")
                        .HasDatabaseName("IX_Students_UpdatedAtUtc");

                    b.ToTable("Students", null, t =>
                        {
                            t.HasTrigger("TR_Students_SetUpdatedAtUtc");

                            t.HasCheckConstraint("CK_Students_Gender", "[gender] IS NULL OR [gender] IN ('MALE', 'FEMALE', 'OTHER')");

                            t.HasCheckConstraint("CK_Students_Status", "[status] IN ('ACTIVE', 'INACTIVE', 'GRADUATED', 'SUSPENDED')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            StudentId = 1001L,
                            CreatedAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(2010, 5, 12),
                            Email = "student.demo@example.test",
                            FullName = "Nguyen Minh Anh",
                            Gender = "FEMALE",
                            GuardianName = "Nguyen Van Minh",
                            GuardianPhone = "0900000011",
                            IsDeleted = false,
                            Phone = "0900000001",
                            Status = "ACTIVE",
                            StudentCode = "STU-DEMO-001",
                            UpdatedAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.Teacher", b =>
                {
                    b.Property<long>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TeacherId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Specialization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("specialization");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'ACTIVE'");

                    b.Property<string>("TeacherCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("teacher_code");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("TeacherId")
                        .HasName("PK_Teachers");

                    b.HasIndex("TeacherCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Teachers_TeacherCode");

                    b.HasIndex("UpdatedAtUtc", "TeacherId")
                        .HasDatabaseName("IX_Teachers_UpdatedAtUtc");

                    b.ToTable("Teachers", null, t =>
                        {
                            t.HasTrigger("TR_Teachers_SetUpdatedAtUtc");

                            t.HasCheckConstraint("CK_Teachers_Status", "[status] IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            TeacherId = 1001L,
                            CreatedAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "teacher.demo@example.test",
                            FullName = "Tran Thu Ha",
                            IsDeleted = false,
                            Phone = "0900000002",
                            Specialization = "General English",
                            Status = "ACTIVE",
                            TeacherCode = "TCH-DEMO-001",
                            UpdatedAtUtc = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("EnglishCenter.Api.Domain.Entities.Student", "Student")
                        .WithOne()
                        .HasForeignKey("EnglishCenter.Api.Domain.Entities.AppUser", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_AppUsers_Students");

                    b.HasOne("EnglishCenter.Api.Domain.Entities.Teacher", "Teacher")
                        .WithOne()
                        .HasForeignKey("EnglishCenter.Api.Domain.Entities.AppUser", "TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_AppUsers_Teachers");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("EnglishCenter.Api.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AttendanceRecords_Enrollments");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.Class", b =>
                {
                    b.HasOne("EnglishCenter.Api.Domain.Entities.Course", "Course")
                        .WithMany("Classes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Classes_Courses");

                    b.HasOne("EnglishCenter.Api.Domain.Entities.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Classes_Teachers");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("EnglishCenter.Api.Domain.Entities.Class", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Enrollments_Classes");

                    b.HasOne("EnglishCenter.Api.Domain.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Enrollments_Students");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.Payment", b =>
                {
                    b.HasOne("EnglishCenter.Api.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany("Payments")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Enrollments");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("EnglishCenter.Api.Domain.Entities.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_AppUsers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.Class", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.Course", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.Enrollment", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("EnglishCenter.Api.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
