@EnglishCenter.Api_HostAddress = http://localhost:8080
@accessToken = REPLACE_WITH_LOCAL_ACCESS_TOKEN

GET {{EnglishCenter.Api_HostAddress}}/api/health
Accept: application/json

###

GET {{EnglishCenter.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{EnglishCenter.Api_HostAddress}}/api/not-found
Accept: application/problem+json

###

GET {{EnglishCenter.Api_HostAddress}}/api/students?page=1&pageSize=20
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{EnglishCenter.Api_HostAddress}}/api/teachers?page=1&pageSize=20
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{EnglishCenter.Api_HostAddress}}/api/courses?page=1&pageSize=20
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{EnglishCenter.Api_HostAddress}}/api/classes?page=1&pageSize=20
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{EnglishCenter.Api_HostAddress}}/api/enrollments?page=1&pageSize=20
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{EnglishCenter.Api_HostAddress}}/api/attendance?page=1&pageSize=20
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{EnglishCenter.Api_HostAddress}}/api/payments?page=1&pageSize=20
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{EnglishCenter.Api_HostAddress}}/api/auth/me
Accept: application/json
Authorization: Bearer {{accessToken}}
